---

variables:
  CI_EL9: "yes"
  CI_SKIP_EL7: "yes"  # TODO: Delete once all EL7 support has been removed

include:
  - project: 'dpres/gitlab-ci-pipeline'
    ref: master
    file:
      - '/pipeline/common.yml'
      - '/pipeline/fddps.yml'
